spin_version = "1"
authors = ["jamesmilligan <james@omnant.co.uk>"]
description = ""
name = "product-page"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "product-page"
source = "main.wasm"
allowed_http_hosts = [ "insecure:allow-all" ]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
[component.config]
services_domain = ""
details_hostname = "10.143.9.10"
details_service_port = "9080"
ratings_hostname = "10.143.9.20"
ratings_service_port = "9080"
reviews_hostname = "10.143.9.30"
reviews_service_port = "9080"
